### ISSUE TITLE
Upgrade to 6.2

### ISSUE THREAD

**Issue by huphtur** [huphtur/jekyll-foundation-zurb-template#1]
Foundation 6.2 now does the Babel thing. I tried their [upgrade instructions](https://github.com/zurb/foundation-sites/wiki/Upgrading-to-Foundation-6.2) but keep failing. Anyone willing to give this a shot?

**Comment by falzar** [comment]
'sass' errored after 271 ms
[19:56:04] TypeError: $.minifyCss is not a function

after npm start 

please help me

**Comment by huphtur** [comment]
@falzar i got all kinds of other errors when upgrading to 6.2. Sorry, I have not been able to fix this :( That's why I asked for help.
